### ISSUE TITLE
network switching option not working

### ISSUE THREAD

**Issue by leosguru** [Trust-Machines/multisafe-ui#4]
Switching from Mainnet to Testnet or vice versa is not working 

following error is logged in browser console 
```
index.mjs:19 Uncaught Error: [@micro-stacks/client] Network switching is currently disabled. Set `enableNetworkSwitching` to `true` to enable.
    at setNetwork (index.mjs:19:14996)
    at onClick (network-switch.tsx:30:25)
    at Object.Ue (react-dom.production.min.js:52:317)
    at qe (react-dom.production.min.js:52:471)
    at react-dom.production.min.js:53:35
    at Pr (react-dom.production.min.js:100:68)
    at Rr (react-dom.production.min.js:101:380)
    at react-dom.production.min.js:113:65
    at Ie (react-dom.production.min.js:292:189)
    at react-dom.production.min.js:50:57

**Comment by talhasch** [comment]
Fixed: https://github.com/Trust-Machines/multisafe-ui/commit/c481aa207c03e8806023b42c47dfead82cae94c8
